2014/06/12 22:58:17 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/main.php:51)
Stack trace:
#0 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#1 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#2 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#3 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#4 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(206): CContentDecorator->run()
#5 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(300): SiteController->endWidget()
#6 /Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/column1.php(6): SiteController->endContent()
#7 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(126): require()
#8 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#9 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(784): SiteController->renderFile()
#10 /Library/WebServer/Documents/MIT/gps_mit/protected/controllers/SiteController.php(32): SiteController->render()
#11 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#12 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#13 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(286): SiteController->runAction()
#14 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#15 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(282): SiteController->run()
#16 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#17 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /Library/WebServer/Documents/MIT/gps_mit/index.php(13): CWebApplication->run()
REQUEST_URI=/MIT/gps_mit/
in /Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/main.php (51)
in /Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/column1.php (6)
in /Library/WebServer/Documents/MIT/gps_mit/protected/controllers/SiteController.php (32)
2014/06/13 15:04:16 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/main.php:51)
Stack trace:
#0 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#1 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#2 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#3 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#4 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(206): CContentDecorator->run()
#5 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(300): SiteController->endWidget()
#6 /Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/column1.php(6): SiteController->endContent()
#7 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(126): require()
#8 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#9 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(784): SiteController->renderFile()
#10 /Library/WebServer/Documents/MIT/gps_mit/protected/controllers/SiteController.php(32): SiteController->render()
#11 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#12 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#13 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(286): SiteController->runAction()
#14 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#15 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(282): SiteController->run()
#16 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#17 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /Library/WebServer/Documents/MIT/gps_mit/index.php(13): CWebApplication->run()
REQUEST_URI=/MIT/gps_mit/
in /Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/main.php (51)
in /Library/WebServer/Documents/MIT/gps_mit/protected/views/layouts/column1.php (6)
in /Library/WebServer/Documents/MIT/gps_mit/protected/controllers/SiteController.php (32)
2014/06/13 10:22:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Library/WebServer/Documents/MIT/gps_mit/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/MIT/gps_mit/index.php?r=gii
---
2014/06/13 10:22:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "giic".' in /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('giic')
#1 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Library/WebServer/Documents/MIT/gps_mit/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/MIT/gps_mit/index.php?r=giic
---
2014/06/13 10:29:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /Library/WebServer/Documents/MIT/gps_mit/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Library/WebServer/Documents/MIT/gps_mit/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /Library/WebServer/Documents/MIT/gps_mit/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/MIT/gps_mit/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/MIT/gps_mit/index.php?r=gii
---
2014/06/13 13:24:50 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/var/www/MIT/gps_mit/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /var/www/MIT/gps_mit/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /var/www/MIT/gps_mit/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/var/www/MIT/gp...')
#1 /var/www/MIT/gps_mit/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /var/www/MIT/gps_mit/yii/framework/gii/GiiModule.php(143): CAssetManager->publish('/var/www/MIT/gp...')
#3 /var/www/MIT/gps_mit/yii/framework/base/CComponent.php(111): GiiModule->getAssetsUrl()
#4 /var/www/MIT/gps_mit/yii/framework/base/CModule.php(105): CComponent->__get('assetsUrl')
#5 /var/www/MIT/gps_mit/yii/framework/gii/views/layouts/main.php(5): CModule->__get('assetsUrl')
#6 /var/www/MIT/gps_mit/yii/framework/web/CBaseController.php(126): require('/var/www/MIT/gp...')
#7 /var/www/MIT/gps_mit/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/MIT/gp...', Array, true)
#8 /var/www/MIT/gps_mit/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/MIT/gp...', Array, true)
#9 /var/www/MIT/gps_mit/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div class="con...')
#10 /var/www/MIT/gps_mit/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div class="con...')
#11 /var/www/MIT/gps_mit/yii/framework/web/CBaseController.php(206): COutputProcessor->run()
#12 /var/www/MIT/gps_mit/yii/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#13 /var/www/MIT/gps_mit/yii/framework/gii/views/layouts/column1.php(7): CBaseController->endContent()
#14 /var/www/MIT/gps_mit/yii/framework/web/CBaseController.php(126): require('/var/www/MIT/gp...')
#15 /var/www/MIT/gps_mit/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/MIT/gp...', Array, true)
#16 /var/www/MIT/gps_mit/yii/framework/web/CController.php(784): CBaseController->renderFile('/var/www/MIT/gp...', Array, true)
#17 /var/www/MIT/gps_mit/yii/framework/gii/controllers/DefaultController.php(47): CController->render('login', Array)
#18 /var/www/MIT/gps_mit/yii/framework/web/actions/CInlineAction.php(49): DefaultController->actionLogin()
#19 /var/www/MIT/gps_mit/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#20 /var/www/MIT/gps_mit/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#21 /var/www/MIT/gps_mit/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 /var/www/MIT/gps_mit/yii/framework/web/CWebApplication.php(282): CController->run('login')
#23 /var/www/MIT/gps_mit/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#24 /var/www/MIT/gps_mit/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#25 /var/www/MIT/gps_mit/index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/MIT/gps_mit/index.php?r=gii/default/login
---
2014/06/16 14:45:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /var/www/MIT/gps_mit/back/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#9 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 14:46:03 [error] [php] move_uploaded_file(uploads/logosam.png): failed to open stream: No such file or directory (/var/www/MIT/gps_mit/back/protected/controllers/SampleController.php:96)
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): SampleController->runAction()
#2 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CAccessControlFilter->filter()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): SampleController->filterAccessControl()
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): SampleController->runActionWithFilters()
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): SampleController->run()
#9 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#10 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /var/www/MIT/gps_mit/back/index.php(13): CWebApplication->run()
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (96)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 15:59:25 [error] [php] Undefined variable: filename (/var/www/MIT/gps_mit/back/protected/controllers/SampleController.php:100)
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): SampleController->runAction()
#1 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CAccessControlFilter->filter()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): SampleController->filterAccessControl()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#5 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): SampleController->runActionWithFilters()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): SampleController->run()
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /var/www/MIT/gps_mit/back/index.php(13): CWebApplication->run()
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (100)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 16:04:40 [error] [exception.CException] exception 'CException' with message 'Property "UploadedFile.updated_at" is not defined.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('updated_at')
#1 /var/www/MIT/gps_mit/back/yii/framework/validators/CRequiredValidator.php(58): CActiveRecord->__get('updated_at')
#2 /var/www/MIT/gps_mit/back/yii/framework/validators/CValidator.php(213): CRequiredValidator->validateAttribute(Object(UploadedFile), 'updated_at')
#3 /var/www/MIT/gps_mit/back/yii/framework/base/CModel.php(159): CValidator->validate(Object(UploadedFile), NULL)
#4 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(805): CModel->validate(NULL)
#5 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#14 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#16 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#17 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:05:41 [error] [exception.CException] exception 'CException' with message 'Property "UploadedFile.updated_at" is not defined.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('updated_at')
#1 /var/www/MIT/gps_mit/back/yii/framework/validators/CRequiredValidator.php(58): CActiveRecord->__get('updated_at')
#2 /var/www/MIT/gps_mit/back/yii/framework/validators/CValidator.php(213): CRequiredValidator->validateAttribute(Object(UploadedFile), 'updated_at')
#3 /var/www/MIT/gps_mit/back/yii/framework/base/CModel.php(159): CValidator->validate(Object(UploadedFile), NULL)
#4 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(805): CModel->validate(NULL)
#5 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#14 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#16 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#17 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:31:57 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.numeric_id" is not defined.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/web/auth/CWebUser.php(146): CComponent->__get('numeric_id')
#1 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(99): CWebUser->__get('numeric_id')
#2 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:34:32 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:173
Stack trace:
#0 /var/www/MIT/gps_mit/back/protected/components/UserIdentity.php(31): CComponent->__set('_id', 456345)
#1 /var/www/MIT/gps_mit/back/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/MIT/gps_mit/back/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/MIT/gps_mit/back/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/MIT/gps_mit/back/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/MIT/gps_mit/back/protected/controllers/SiteController.php(94): CModel->validate()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=site/login
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=site/login
---
2014/06/16 16:34:53 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.id" is read only.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:170
Stack trace:
#0 /var/www/MIT/gps_mit/back/protected/components/UserIdentity.php(31): CComponent->__set('id', 456345)
#1 /var/www/MIT/gps_mit/back/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/MIT/gps_mit/back/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/MIT/gps_mit/back/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/MIT/gps_mit/back/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/MIT/gps_mit/back/protected/controllers/SiteController.php(94): CModel->validate()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=site/login
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=site/login
---
2014/06/16 16:37:14 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.getId" is not defined.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/web/auth/CWebUser.php(146): CComponent->__get('getId')
#1 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(99): CWebUser->__get('getId')
#2 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:39:56 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: "1402954796"
LINE 1: ...("created_at", "identity_id", "filename") VALUES ('140295479...
                                                             ^. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2).
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (101)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 16:39:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: "1402954796"
LINE 1: ...("created_at", "identity_id", "filename") VALUES ('140295479...
                                                             ^. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2)' in /var/www/MIT/gps_mit/back/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(1077): CDbCommand->execute()
#1 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#14 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:40:04 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: "1402954804"
LINE 1: ...("created_at", "identity_id", "filename") VALUES ('140295480...
                                                             ^. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2).
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (101)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 16:40:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type timestamp: "1402954804"
LINE 1: ...("created_at", "identity_id", "filename") VALUES ('140295480...
                                                             ^. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2)' in /var/www/MIT/gps_mit/back/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(1077): CDbCommand->execute()
#1 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#14 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:44:57 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "uploaded_file" violates foreign key constraint "identity_uploaded_file_fk"
DETAIL:  Key (identity_id)=(456345) is not present in table "identity".. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2).
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (101)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 16:44:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "uploaded_file" violates foreign key constraint "identity_uploaded_file_fk"
DETAIL:  Key (identity_id)=(456345) is not present in table "identity".. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2)' in /var/www/MIT/gps_mit/back/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(1077): CDbCommand->execute()
#1 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#14 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:47:16 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "uploaded_file" violates foreign key constraint "identity_uploaded_file_fk"
DETAIL:  Key (identity_id)=(456345) is not present in table "identity".. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2).
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (101)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 16:47:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "uploaded_file" violates foreign key constraint "identity_uploaded_file_fk"
DETAIL:  Key (identity_id)=(456345) is not present in table "identity".. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2)' in /var/www/MIT/gps_mit/back/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(1077): CDbCommand->execute()
#1 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#14 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 16:47:25 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "uploaded_file" violates foreign key constraint "identity_uploaded_file_fk"
DETAIL:  Key (identity_id)=(456345) is not present in table "identity".. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2).
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (101)
in /var/www/MIT/gps_mit/back/index.php (13)
2014/06/16 16:47:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "uploaded_file" violates foreign key constraint "identity_uploaded_file_fk"
DETAIL:  Key (identity_id)=(456345) is not present in table "identity".. The SQL statement executed was: INSERT INTO "uploaded_file" ("created_at", "identity_id", "filename") VALUES (:yp0, :yp1, :yp2)' in /var/www/MIT/gps_mit/back/yii/framework/db/CDbCommand.php:358
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(1077): CDbCommand->execute()
#1 /var/www/MIT/gps_mit/back/yii/framework/db/ar/CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php(101): CActiveRecord->save()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SampleController->actionUpload()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#11 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('upload')
#13 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('sample/upload')
#14 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=sample/create
---
2014/06/16 17:54:10 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._456345" is not defined.' in /var/www/MIT/gps_mit/back/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/MIT/gps_mit/back/protected/components/UserIdentity.php(44): CComponent->__get('_456345')
#1 /var/www/MIT/gps_mit/back/yii/framework/web/auth/CWebUser.php(229): UserIdentity->getId()
#2 /var/www/MIT/gps_mit/back/protected/models/LoginForm.php(71): CWebUser->login(Object(UserIdentity), 0)
#3 /var/www/MIT/gps_mit/back/protected/controllers/SiteController.php(94): LoginForm->login()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#5 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): CController->run('login')
#9 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#10 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#11 /var/www/MIT/gps_mit/back/index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/MIT/gps_mit/back/index.php?r=site/login
HTTP_REFERER=http://localhost/MIT/gps_mit/back/index.php?r=site/login
---
2014/06/16 17:55:29 [error] [php] Undefined variable: fileName (/var/www/MIT/gps_mit/back/protected/controllers/SampleController.php:97)
Stack trace:
#0 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(133): SampleController->runAction()
#1 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#2 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(1145): CAccessControlFilter->filter()
#3 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CInlineFilter.php(58): SampleController->filterAccessControl()
#4 /var/www/MIT/gps_mit/back/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()
#5 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/MIT/gps_mit/back/yii/framework/web/CController.php(265): SampleController->runActionWithFilters()
#7 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(282): SampleController->run()
#8 /var/www/MIT/gps_mit/back/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#9 /var/www/MIT/gps_mit/back/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /var/www/MIT/gps_mit/back/index.php(13): CWebApplication->run()
REQUEST_URI=/MIT/gps_mit/back/index.php?r=sample/upload
in /var/www/MIT/gps_mit/back/protected/controllers/SampleController.php (97)
in /var/www/MIT/gps_mit/back/index.php (13)
